conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib.auth.decorators import permission_required
from django.contrib import admin

from ikwen_webnode.webnode.views import Home, FlatPageView
from ikwen_foulassi.school.views import SchoolDetail
from ikwen_foulassi.foulassi.views import HomeSaaS as scolarfleet

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/serviceDetail/$', permission_required('accesscontrol.sudo')(SchoolDetail.as_view()),
        name='service_detail'),
    url(r'^ikwen/serviceDetail/(?P<service_id>[-\w]+)/$',
        permission_required('accesscontrol.sudo')(SchoolDetail.as_view()),  name='service_detail'),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^scolarfleet$', scolarfleet.as_view(), name='scolarfleet'),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^', include('ikwen_webnode.webnode.urls', namespace='webnode')),
)

foulassi/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from ikwen_foulassi.foulassi.views import KidList, KidDetail, ShowJustificatory, AccessDenied, \
    Home, HomeSaaS, SearchSchool, EventList, DeployCloud, SuccessfulDeployment, AdminHome, ChangeHomework, \
    DownloadApp, TermsAndConditions, DownloadCorrection, BuyWebsite
from ikwen_foulassi.foulassi.cash_in import confirm_invoice_payment, confirm_my_kids_payment,\
    confirm_correction_payment

urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^for-schools$', HomeSaaS.as_view(), name='home_saas'),
    url(r'^events/$', permission_required('foulassi.ik_view_event')(EventList.as_view()), name='event_list'),
    url(r'^scolarfleet/deploy$', login_required(DeployCloud.as_view()), name='deploy_cloud'),
    url(r'^terms-and-conditions/$', login_required(TermsAndConditions.as_view()), name='terms_and_conditions'),
    url(r'^successfulDeployment/(?P<ikwen_name>[-\w]+)$', login_required(SuccessfulDeployment.as_view()), name='successful_deployment'),
    url(r'^home/$', AdminHome.as_view(), name='admin_home'),
    url(r'^buyWebsite/(?P<school_name>[-\w]+)$', login_required(BuyWebsite.as_view()), name='buy_website'),

    url(r'^search/$', login_required(SearchSchool.as_view()), name='search_school'),
    url(r'^downloadApp/$', DownloadApp.as_view(), name='download_app'),
    url(r'^kids/$', login_required(KidList.as_view()), name='kid_list'),
    url(r'^accessDenied/$', AccessDenied.as_view(), name='access_denied'),
    url(r'^confirm_invoice_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_invoice_payment, name='confirm_invoice_payment'),
    url(r'^confirm_my_kids_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_my_kids_payment, name='confirm_my_kids_payment'),
    url(r'^confirm_correction_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_correction_payment, name='confirm_correction_payment'),

    url(r'^(?P<ikwen_name>[-\w]+)/kid/(?P<student_id>[-\w]+)/(?P<assignment_id>[-\w]+)/download-correction$',
        login_required(DownloadCorrection.as_view()), name='download_correction'),
    url(r'^(?P<ikwen_name>[-\w]+)/kid/(?P<student_id>[-\w]+)$', login_required(KidDetail.as_view()), name='kid_detail'),
    url(r'^(?P<ikwen_name>[-\w]+)/kid/(?P<student_id>[-\w]+)/(?P<assignment_id>[-\w]+)$', login_required(ChangeHomework.as_view()), name='change_homework'),
    url(r'^(?P<ikwen_name>[-\w]+)/kid/(?P<student_id>[-\w]+)/(?P<assignment_id>[-\w]+)/(?P<homework_id>[-\w]+)$', login_required(ChangeHomework.as_view()), name='change_homework'),
    url(r'^(?P<ikwen_name>[-\w]+)/justificatory/(?P<object_id>[-\w]+)$', login_required(ShowJustificatory.as_view()),
        name='show_justificatory'),
)

reporting/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import permission_required
from ikwen_foulassi.reporting.views import Dashboard, DisciplineDetail, generate_report_cards, ReportCardDownloadList, \
    ReportCardHeaderList, ChangeReportCardHeader

urlpatterns = patterns(
    '',
    url(r'^dashboard/$', permission_required('reporting.ik_view_dashboard')(Dashboard.as_view()), name='dashboard'),
    url(r'^disciplineDetail/$', permission_required('reporting.ik_view_dashboard')(DisciplineDetail.as_view()), name='discipline_detail'),

    url(r'^reportCardHeaders/$', permission_required('reporting.ik_manage_reporting')(ReportCardHeaderList.as_view()), name='reportcardheader_list'),
    url(r'^reportCardHeader/$', permission_required('reporting.ik_manage_reporting')(ChangeReportCardHeader.as_view()), name='change_reportcardheader'),
    url(r'^reportCardHeader/(?P<object_id>[-\w]+)/$', permission_required('reporting.ik_manage_reporting')(ChangeReportCardHeader.as_view()), name='change_reportcardheader'),

    url(r'^downloadList/(?P<session_id>[-\w]+)/$', permission_required('reporting.ik_manage_reporting')(ReportCardDownloadList.as_view()), name='report_card_download_list'),
    url(r'^downloadList/(?P<session_id>[-\w]+)/(?P<classroom_id>[-\w]+)/$', permission_required('reporting.ik_manage_reporting')(ReportCardDownloadList.as_view()), name='report_card_download_list'),
    url(r'^generate_report_cards$', generate_report_cards, name='generate_report_cards'),
)

school/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import permission_required, user_passes_test
from ikwen_foulassi.school.student.views import ChangeStudent, StudentDetail, ChangeJustificatory, ViewHomework,\
    ViewCorrection
from ikwen_foulassi.school.classroom.views import ClassroomList, ChangeClassroom, ClassroomDetail, upload_student_file, \
    AssignmentList, ChangeAssignment, ChangeAssignmentCorrection, AssignmentCorrectionList, AssignmentReplyList
from ikwen_foulassi.school.views import LevelList, ChangeLevel, SubjectList, ChangeSubject, ChangeSession, \
    SessionList, DisciplineItemList, ChangeDisciplineItem, TeacherList, TeacherDetail, SessionGroupList, \
    ChangeSessionGroup, close_session
from ikwen_foulassi.foulassi.utils import access_classroom

urlpatterns = patterns(
    '',
    url(r'^levels/$', permission_required('school.ik_manage_school')(LevelList.as_view()), name='level_list'),
    url(r'^level/$', permission_required('school.ik_manage_school')(ChangeLevel.as_view()), name='change_level'),
    url(r'^level/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeLevel.as_view()), name='change_level'),

    url(r'^subjects/$', permission_required('school.ik_manage_school')(SubjectList.as_view()), name='subject_list'),
    url(r'^subject/$', permission_required('school.ik_manage_school')(ChangeSubject.as_view()), name='change_subject'),
    url(r'^subject/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSubject.as_view()),
        name='change_subject'),

    url(r'^sessions/$', permission_required('school.ik_manage_school')(SessionList.as_view()), name='session_list'),
    url(r'^session/$', permission_required('school.ik_manage_school')(ChangeSession.as_view()), name='change_session'),
    url(r'^session/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSession.as_view()),
        name='change_session'),

    url(r'^sessionGroups/$', permission_required('school.ik_manage_school')(SessionGroupList.as_view()), name='sessiongroup_list'),
    url(r'^sessionGroup/$', permission_required('school.ik_manage_school')(ChangeSessionGroup.as_view()), name='change_sessiongroup'),
    url(r'^sessionGroup/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSessionGroup.as_view()),
        name='change_sessiongroup'),

    url(r'^discipline/$', permission_required('school.ik_manage_school')(DisciplineItemList.as_view()), name='disciplineitem_list'),
    url(r'^disciplineItem/$', permission_required('school.ik_manage_school')(ChangeDisciplineItem.as_view()), name='change_disciplineitem'),
    url(r'^disciplineItem/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeDisciplineItem.as_view()),
        name='change_disciplineitem'),

    url(r'^classrooms/$', user_passes_test(access_classroom)(ClassroomList.as_view()), name='classroom_list'),
    url(r'^classroom/$', permission_required('school.ik_manage_school')(ChangeClassroom.as_view()), name='change_classroom'),
    url(r'^classroom/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeClassroom.as_view()),
        name='change_classroom'),
    url(r'^classroomDetail/(?P<object_id>[-\w]+)/$', user_passes_test(access_classroom)(ClassroomDetail.as_view()),
        name='classroom_detail'),

    url(r'^assignments/$', user_passes_test(access_classroom)(AssignmentList.as_view()), name='assignment_list'),
    url(r'^assignment/(?P<classroom_id>[-\w]+)/$', user_passes_test(access_classroom)(ChangeAssignment.as_view()),
        name='change_assignment'),
    url(r'^assignment/(?P<classroom_id>[-\w]+)/(?P<object_id>[-\w]+)/$',
        user_passes_test(access_classroom)(ChangeAssignment.as_view()), name='change_assignment'),
    url(r'^correction/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)/$',
        user_passes_test(access_classroom)(ChangeAssignmentCorrection.as_view()), name='change_assignment_correction'),
    url(r'^correction/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)/(?P<object_id>[-\w]+)$',
        user_passes_test(access_classroom)(ChangeAssignmentCorrection.as_view()), name='change_assignment_correction'),
    url(r'^corrections/(?P<classroom_id>[-\w]+)/(?P<subject_id>[-\w]+)$', user_passes_test(access_classroom)(AssignmentCorrectionList.as_view()),
        name='assignment_correction_list'),
    url(r'^replies/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)$', user_passes_test(access_classroom)(AssignmentReplyList.as_view()),
        name='assignment_reply_list'),
    url(r'^homework/(?P<object_id>[-\w]+)/$', user_passes_test(access_classroom)(ViewHomework.as_view()),
        name='view_homework'),
    url(r'^homework/(?P<homework_id>[-\w]+)/correction$', user_passes_test(access_classroom)(ViewCorrection.as_view()),
        name='view_correction'),

    url(r'^upload_student_file/$', permission_required('foulassi.ik_manage_student')(upload_student_file), name='upload_student_file'),
    url(r'^newStudent/(?P<classroom_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(ChangeStudent.as_view()), name='change_student'),
    url(r'^student/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(StudentDetail.as_view()),
        name='student_detail'),
    url(r'^justificatory/$', permission_required('foulassi.ik_manage_student')(ChangeJustificatory.as_view()),
        name='change_justificatory'),
    url(r'^justificatory/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(ChangeJustificatory.as_view()),
        name='change_justificatory'),

    url(r'^teachers/$', permission_required('foulassi.ik_manage_teacher')(TeacherList.as_view()), name='teacher_list'),
    url(r'^teacher/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_teacher')(TeacherDetail.as_view()), name='teacher_detail'),
    url(r'^close_session$', close_session, name='close_session'),
)

templates/core/app_base_admin.html
{% extends "core/base_admin.html" %}
{% load i18n static %}

{% block app_admin_nav %}
    {% if perms.school.ik_view_dashboard %}
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="home">
            <a href="{% url 'foulassi:admin_home' %}">{% trans "Home" %}</a>
        </li>
    </ul>
    <div class="divider"></div>
    {% endif %}
    {% if perms.school.ik_view_dashboard %}
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="full-dashboard">
            <a href="{% url 'reporting:dashboard' %}">{% trans "Dashboard" %}</a>
        </li>
        <li role="presentation" class="dashboard">
            <a href="{% url 'ikwen:dashboard' %}">{% trans "Finance Dashboard" %}</a>
        </li>
    </ul>
    <div class="divider"></div>
    {% endif %}
    <ul class="nav nav-pills nav-stacked">
        {% if perms.school.ik_manage_school %}
        <li role="presentation" class="subjects">
            {% url 'school:subject_list' as subject_list_url %}
            <a href="{{ subject_list_url }}">{% trans "Subjects" %}</a>
        </li>
        {% endif %}
        {% if perms.school.ik_manage_school %}
        <li role="presentation" class="levels">
            {% url 'school:level_list' as level_list_url %}
            <a href="{{ level_list_url }}">{% trans "Levels" %}</a>
        </li>
        {% endif %}
        {% if perms.school.ik_manage_school or perms.school.ik_access_scores %}
        <li role="presentation" class="classrooms">
            {% url 'school:classroom_list' as classroom_list_url %}
            <a href="{{ classroom_list_url }}">{% trans "Classrooms" %}</a>
        </li>
        {% endif %}
        {% if perms.foulassi.ik_manage_teacher %}
        <li role="presentation" class="teachers">
            {% url 'school:teacher_list' as teacher_list_url %}
            <a href="{{ teacher_list_url }}">{% trans "Teachers" %}</a>
        </li>
        {% endif %}
    </ul>
    {% if perms.school.ik_manage_school %}
    <div class="divider"></div>
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="session-groups">
            {% url 'school:sessiongroup_list' as sessiongroup_list_url %}
            <a href="{{ sessiongroup_list_url }}">{% trans "Session Groups" %}</a>
        </li>
        <li role="presentation" class="sessions">
            {% url 'school:session_list' as session_list_url %}
            <a href="{{ session_list_url }}">{% trans "Sessions" %}</a>
        </li>
        <li role="presentation" class="report-card-headers">
            {% url 'reporting:reportcardheader_list' as reportcardheader_list_url %}
            <a href="{{ reportcardheader_list_url }}">{% trans "Report Card headers" %}</a>
        </li>
    </ul>
    {% endif %}
    {% if perms.billing.ik_manage_invoice or perms.billing.ik_view_transaction_log %}
    <div class="divider"></div>
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="billing">
            <a href="javascript:;" data-toggle="collapse" data-target="#billing"
               aria-expanded="true" style="padding-right: 0;"> {% trans "Billing" context "Financial transactions" %}
                <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="billing" class="nav nav-pills nav-stacked collapse" aria-expanded="true"
                style="padding-left: 15px">
                <li role="presentation" class="payments">{% url 'billing:payment_list' as payment_list_url %}
                    <a href="{{ payment_list_url }}">{% trans "Payments" %}</a>
                </li>
                {% if perms.billing.ik_view_transaction_log %}
                <li role="presentation" class="transactions">{% url 'billing:transaction_log' as transaction_log_url %}
                    <a href="{{ transaction_log_url }}">{% trans "Transactions" %}</a>
                </li>
                {% endif %}
                {% if perms.accesscontrol.sudo %}
                <li role="presentation" class="wallet">{% url 'cashout:home' as wallet_url %}
                    <a href="{{ wallet_url }}">{% trans "Wallet" %}</a>
                </li>
                {% endif %}
            </ul>
        </li>
    </ul>
    {% endif %}
    {% if perms.school.ik_webmaster %}
    <div class="divider"></div>
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="website-admin">
            {% if website_is_activate %}
                <a href="javascript:;" data-toggle="collapse" data-target="#website-admin"
                   aria-expanded="true" style="padding-right: 0;"> {% trans "Website Admin" %}
                    <i class="fa fa-fw fa-caret-down"></i>
                </a>
                <ul id="website-admin" class="nav nav-pills nav-stacked collapse" aria-expanded="true"
                    style="padding-left: 15px">
                    <li role="presentation" class="homepage">
                        {% url 'web:banner_list' as banner_list_url %}
                        <a href="{{ banner_list_url }}">{% trans "Homepage" %}</a>
                    </li>
                    <li role="presentation" class="menus">{% url 'web:smart_category_list' as smart_category_list_url %}
                        <a href="{{ smart_category_list_url }}">{% trans "Menus" %}</a>
                    </li>
                    <li role="presentation" class="items">{% url 'items:item_list' as item_url %}
                        <a href="{{ item_url }} ">{% trans "Items" %}</a>
                    </li>
                </ul>
            {% else %}
                <a href="{% if has_subscribed_website_service %}{% url 'billing:invoice_list' %}{% else %}{% url 'foulassi:buy_website' service.project_name_slug %}{% endif %}" target="_blank" data-toggle="collapse" data-target="#website-admin"
                   aria-expanded="true" style="padding-right: 12px;"> {% trans "Website" %}
                    <i class="badge badge-danger" style="background-color: rgba(7,156,23,0.92)">activate</i>
                </a>
            {% endif %}
        </li>
    </ul>
    <div class="divider"></div>
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="blog">
            <a href="javascript:;" data-toggle="collapse" data-target="#blog"
               aria-expanded="true" style="padding-right: 0;"> {% trans "Blog" %}
                <i class="fa fa-fw fa-caret-down"></i>
            </a>
            <ul id="blog" class="nav nav-pills nav-stacked collapse" aria-expanded="true"
                style="padding-left: 15px">
                <li class="blog-categories">{% url 'blog:list_category' as category_list_url %}
                    <a href="{{ category_list_url }}">{% trans "Blog categories" %}</a>
                </li>
                <li class="posts">
                    <a href="{% url 'blog:list_post' %}">{% trans "Posts" %}</a>
                </li>
                <li class="comments">
                    <a href="{% url 'blog:list_comment' %}">{% trans "Comments" %}</a>
                </li>
            </ul>
        </li>
    </ul>
    {% endif %}
{% endblock %}