conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib.auth.decorators import permission_required
from django.contrib import admin

from ikwen_webnode.webnode.views import Home, FlatPageView
from ikwen_foulassi.school.views import SchoolDetail
from ikwen_foulassi.foulassi.views import HomeSaaS as scolarfleet

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/serviceDetail/$', permission_required('accesscontrol.sudo')(SchoolDetail.as_view()),
        name='service_detail'),
    url(r'^ikwen/serviceDetail/(?P<service_id>[-\w]+)/$',
        permission_required('accesscontrol.sudo')(SchoolDetail.as_view()),  name='service_detail'),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^scolarfleet$', scolarfleet.as_view(), name='scolarfleet'),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^', include('ikwen_webnode.webnode.urls', namespace='webnode')),
)

school/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import permission_required, user_passes_test
from ikwen_foulassi.school.student.views import ChangeStudent, StudentDetail, ChangeJustificatory, ViewHomework,\
    ViewCorrection
from ikwen_foulassi.school.classroom.views import ClassroomList, ChangeClassroom, ClassroomDetail, upload_student_file, \
    AssignmentList, ChangeAssignment, ChangeAssignmentCorrection, AssignmentCorrectionList, AssignmentReplyList
from ikwen_foulassi.school.views import LevelList, ChangeLevel, SubjectList, ChangeSubject, ChangeSession, \
    SessionList, DisciplineItemList, ChangeDisciplineItem, TeacherList, TeacherDetail, SessionGroupList, \
    ChangeSessionGroup, close_session
from ikwen_foulassi.foulassi.utils import access_classroom

urlpatterns = patterns(
    '',
    url(r'^levels/$', permission_required('school.ik_manage_school')(LevelList.as_view()), name='level_list'),
    url(r'^level/$', permission_required('school.ik_manage_school')(ChangeLevel.as_view()), name='change_level'),
    url(r'^level/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeLevel.as_view()), name='change_level'),

    url(r'^subjects/$', permission_required('school.ik_manage_school')(SubjectList.as_view()), name='subject_list'),
    url(r'^subject/$', permission_required('school.ik_manage_school')(ChangeSubject.as_view()), name='change_subject'),
    url(r'^subject/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSubject.as_view()),
        name='change_subject'),

    url(r'^sessions/$', permission_required('school.ik_manage_school')(SessionList.as_view()), name='session_list'),
    url(r'^session/$', permission_required('school.ik_manage_school')(ChangeSession.as_view()), name='change_session'),
    url(r'^session/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSession.as_view()),
        name='change_session'),

    url(r'^sessionGroups/$', permission_required('school.ik_manage_school')(SessionGroupList.as_view()), name='sessiongroup_list'),
    url(r'^sessionGroup/$', permission_required('school.ik_manage_school')(ChangeSessionGroup.as_view()), name='change_sessiongroup'),
    url(r'^sessionGroup/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSessionGroup.as_view()),
        name='change_sessiongroup'),

    url(r'^discipline/$', permission_required('school.ik_manage_school')(DisciplineItemList.as_view()), name='disciplineitem_list'),
    url(r'^disciplineItem/$', permission_required('school.ik_manage_school')(ChangeDisciplineItem.as_view()), name='change_disciplineitem'),
    url(r'^disciplineItem/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeDisciplineItem.as_view()),
        name='change_disciplineitem'),

    url(r'^classrooms/$', user_passes_test(access_classroom)(ClassroomList.as_view()), name='classroom_list'),
    url(r'^classroom/$', permission_required('school.ik_manage_school')(ChangeClassroom.as_view()), name='change_classroom'),
    url(r'^classroom/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeClassroom.as_view()),
        name='change_classroom'),
    url(r'^classroomDetail/(?P<object_id>[-\w]+)/$', user_passes_test(access_classroom)(ClassroomDetail.as_view()),
        name='classroom_detail'),

    url(r'^assignments/$', user_passes_test(access_classroom)(AssignmentList.as_view()), name='assignment_list'),
    url(r'^assignment/(?P<classroom_id>[-\w]+)/$', user_passes_test(access_classroom)(ChangeAssignment.as_view()),
        name='change_assignment'),
    url(r'^assignment/(?P<classroom_id>[-\w]+)/(?P<object_id>[-\w]+)/$',
        user_passes_test(access_classroom)(ChangeAssignment.as_view()), name='change_assignment'),
    url(r'^correction/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)/$',
        user_passes_test(access_classroom)(ChangeAssignmentCorrection.as_view()), name='change_assignment_correction'),
    url(r'^correction/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)/(?P<object_id>[-\w]+)$',
        user_passes_test(access_classroom)(ChangeAssignmentCorrection.as_view()), name='change_assignment_correction'),
    url(r'^corrections/(?P<classroom_id>[-\w]+)/(?P<subject_id>[-\w]+)$', user_passes_test(access_classroom)(AssignmentCorrectionList.as_view()),
        name='assignment_correction_list'),
    url(r'^replies/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)$', user_passes_test(access_classroom)(AssignmentReplyList.as_view()),
        name='assignment_reply_list'),
    url(r'^homework/(?P<object_id>[-\w]+)/$', user_passes_test(access_classroom)(ViewHomework.as_view()),
        name='view_homework'),
    url(r'^homework/(?P<homework_id>[-\w]+)/correction$', user_passes_test(access_classroom)(ViewCorrection.as_view()),
        name='view_correction'),

    url(r'^upload_student_file/$', permission_required('foulassi.ik_manage_student')(upload_student_file), name='upload_student_file'),
    url(r'^newStudent/(?P<classroom_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(ChangeStudent.as_view()), name='change_student'),
    url(r'^student/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(StudentDetail.as_view()),
        name='student_detail'),
    url(r'^justificatory/$', permission_required('foulassi.ik_manage_student')(ChangeJustificatory.as_view()),
        name='change_justificatory'),
    url(r'^justificatory/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(ChangeJustificatory.as_view()),
        name='change_justificatory'),

    url(r'^teachers/$', permission_required('foulassi.ik_manage_teacher')(TeacherList.as_view()), name='teacher_list'),
    url(r'^teacher/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_teacher')(TeacherDetail.as_view()), name='teacher_detail'),
    url(r'^close_session$', close_session, name='close_session'),
)

school/models.py
from datetime import datetime

from django.utils import timezone
from django.core.exceptions import MultipleObjectsReturned
from django.db import models
from django_mongodb_engine.contrib import MongoDBManager
from djangotoolbox.fields import ListField, EmbeddedModelField

from ikwen.accesscontrol.models import Member
from ikwen.core.models import Model
from ikwen.core.fields import FileField
from django.utils.translation import gettext_lazy as _
from ikwen_foulassi.foulassi.models import Student, Teacher, ResultsTracker, get_school_year


# ikwen Events
STUDENT_EXCLUDED = "StudentExcluded"


class Level(Model, ResultsTracker):
    """
    A school level
    """
    name = models.CharField(_("Name"), max_length=30,
                            help_text=_("<strong>Eg:</strong> Form1, Form2, ..."))
    slug = models.SlugField()
    registration_fees = models.IntegerField(_("Registration fees"), default=0)
    first_instalment = models.IntegerField(_("First instalment"), default=0)
    second_instalment = models.IntegerField(_("Second instalment"), default=0)
    third_instalment = models.IntegerField(_("Third instalment"), default=0)
    order_of_appearance = models.IntegerField(default=0)
    subject_coefficient_list = ListField(EmbeddedModelField('SubjectCoefficient'))

    class Meta:
        unique_together = (
            ('name', 'school_year'),
            ('slug', 'school_year'),
        )
        ordering = ('order_of_appearance', 'name')

    def __unicode__(self):
        return self.name


class Classroom(Model, ResultsTracker):
    STUDENT_THRESHOLD = 3  # Threshold above which we consider student were consistently populated
    OUT_OF_20 = "OutOf20"
    ABC = "ABC"
    NA = "N/A"

    level = models.ForeignKey(Level, verbose_name=_("Level"))
    name = models.CharField(_("Name"), max_length=30,
                            help_text=_("Raw name of the class. Don't write the level again. <br>Eg: A, B ... "
                                        "The level will be added to get the full name."))
    slug = models.SlugField()
    registration_fees = models.IntegerField(_("Registration fees"), default=0)
    first_instalment = models.IntegerField(_("First instalment"), default=0)
    second_instalment = models.IntegerField(_("Second instalment"), default=0)
    third_instalment = models.IntegerField(_("Third instalment"), default=0)
    professor = models.ForeignKey(Teacher, verbose_name=_("Professor"), blank=True, null=True)
    leader = models.ForeignKey(Student, related_name='leaders', blank=True, null=True)
    subject_coefficient_list = ListField(EmbeddedModelField('SubjectCoefficient'))
    has_parent_reminder = models.BooleanField(default=False)
    has_student_reminder = models.BooleanField(default=False)
    mark_students = models.BooleanField(_("Mark students ?"), default=True,
                                        help_text=_("Check if students of this classroom receive scores after "
                                                    "evaluation. Uncheck if not. For example uncheck for nursery "
                                                    "classrooms as they are not really marked."))
    marking = models.BooleanField(_("Students marking"), default=OUT_OF_20,
                                  help_text=_("Select how we mark students in this classroom ."))

    class Meta:
        unique_together = ('level', 'name', 'school_year')
        ordering = ('level', 'name')
        permissions = (
            ("ik_access_scores", "Can view and edit student scores"),
        )

    def __unicode__(self):
        return str(self.level).decode('utf8') + ' ' + self.name

    def __cmp__(self, other):
        if self.name == other.name:
            return 0
        return 1 if self.name > other.name else -1

    def _get_size(self):
        return self.student_count
    size = property(_get_size)


class Subject(Model):
    name = models.CharField(_("Name"), max_length=60, unique=True)
    slug = models.SlugField(unique=True)
    is_visible = models.BooleanField(default=True)

    class Meta:
        ordering = ('name', )

    def __unicode__(self):
        return self.name

    def get_teacher(self, classroom):
        responsibilities = TeacherResponsibility.objects\
            .raw_query({'classroom_fk_list': {'$elemMatch': {'$eq': classroom.id}}})\
            .select_related('teacher').filter(subject=self)
        try:
            return responsibilities[0].teacher
        except:
            pass

    def set_teacher(self, classroom, teacher):
        responsibility, update = TeacherResponsibility.objects.get_or_create(teacher=teacher, subject=self)
        if classroom.id not in responsibility.classroom_fk_list:
            responsibility.classroom_fk_list.append(classroom.id)
        responsibility.save()


class SubjectCoefficient(models.Model):
    subject = models.ForeignKey(Subject)
    group = models.IntegerField(default=0)
    coefficient = models.IntegerField(default=1)
    lessons_due = models.IntegerField(default=0)
    hours_due = models.IntegerField(default=0)

    def __cmp__(self, other):
        self_subject = self.subject  # Avoids multiple database queries
        other_subject = other.subject

        if self.group == other.group:
            if self_subject.name == other_subject.name:
                return 0
            return 1 if self_subject.name > other_subject.name else -1
        return 1 if self.group > other.group else -1


class TeacherResponsibility(Model):
    teacher = models.ForeignKey(Teacher)
    subject = models.ForeignKey(Subject)
    classroom_fk_list = ListField()

    objects = MongoDBManager()

    class Meta:
        unique_together = ('teacher', 'subject', )


def get_subject_list(obj, using='default'):
    """
    Gets a list of Subject of classes having the field
    subject_coefficient_list: Level and Classroom
    Every Subject in the returned list has additional fields
    group, coefficient, lessons_due, and hours_due for easy access to them
    """
    subject_list = []
    for item in obj.subject_coefficient_list:
        try:
            subject = Subject.objects.using(using).get(pk=item.__dict__['subject_id'])
            subject.group = item.group
            subject.coefficient = item.coefficient
            subject.lessons_due = item.lessons_due
            subject.hours_due = item.hours_due
            subject_list.append(subject)
        except Subject.DoesNotExist:
            obj.subject_coefficient_list.remove(item)
    obj.save(using=using)
    return subject_list


# def clean_subject_list(obj):
#     """
#     Goes through a list of Subject of classes having the field
#     subject_list: Level and Classroom and removes unexisting Subject
#     """
#     for item in obj.subject_list:
#         try:
#             item.subject
#         except Subject.DoesNotExist:
#             obj.subject_list.remove(item)
#     obj.save()


class SessionGroup(Model, ResultsTracker):
    """
    A group of exam sessions (Term, Semester, ...)
    """
    name = models.CharField(_("Name"), max_length=60)
    slug = models.SlugField(blank=True, null=True)
    starts_on = models.DateField(_("Starts on"), default=datetime.now)
    ends_on = models.DateField(_("Ends on"), default=datetime.now)

    class Meta:
        ordering = ('id', 'name', )
        unique_together = ('name', 'school_year', )

    def __unicode__(self):
        return self.name

    def _get_order_number(self):
        all_sessions = list(SessionGroup.objects.filter(school_year=get_school_year()))
        return all_sessions.index(self)
    order_number = property(_get_order_number)

    def get_obj_details(self):
        return self.starts_on.strftime('%Y, %m/%d') + ' - ' + self.ends_on.strftime('%Y, %m/%d')


class Session(Model, ResultsTracker):
    """
    An examination session
    """
    name = models.CharField(_("Name"), max_length=60)
    slug = models.SlugField(blank=True, null=True)
    session_group = models.ForeignKey(SessionGroup, verbose_name=_("Session group"), blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_current = models.BooleanField(default=False)
    all_scores_set_on = models.DateTimeField(blank=True, null=True)
    report_cards_generated_on = models.DateTimeField(blank=True, null=True)
    starts_on = models.DateField(default=datetime.now)
    ends_on = models.DateField(default=datetime.now)

    class Meta:
        ordering = ('id', )
        unique_together = ('name', 'school_year')

    def __unicode__(self):
        return u"%s: %s" % (self.session_group.name, self.name)

    def _get_order_number(self):
        all_sessions = list(Session.objects.filter(school_year=get_school_year()))
        return all_sessions.index(self)
    order_number = property(_get_order_number)

    def get_obj_details(self):
        return self.starts_on.strftime('%Y, %m/%d') + ' - ' + self.ends_on.strftime('%Y, %m/%d')

    @staticmethod
    def get_current():
        try:
            session = Session.objects.get(is_current=True, school_year=get_school_year())
        except Session.DoesNotExist:
            try:
                session = Session.objects.filter(school_year=get_school_year())[0]
                session.is_current = True
                session.save()
            except IndexError:
                return None
        except MultipleObjectsReturned:
            session = Session.objects.filter(is_current=True, school_year=get_school_year()).order_by('-id')[0]
            Session.objects.exclude(pk=session.id).update(is_current=False)
        return session


class Lesson(Model):
    """
    Lesson taught by a teacher in a Classroom session
    """
    classroom = models.ForeignKey(Classroom, verbose_name=_("Classroom"))
    subject = models.ForeignKey(Subject, verbose_name=_("Subject"))
    teacher = models.ForeignKey(Teacher, verbose_name=_("Teacher"))

school/templates/school/classroom/assignment_reply_list.html
{% extends 'core/object_list_base.html' %}
{% load i18n %}
{% block breadcrumb_location %}
    <li>
        <a href="{% url 'school:classroom_list' %}">{% trans "Classrooms" %}</a>
    </li>
    <li>
        <a href="{% url 'school:classroom_detail' classroom.id %}">{{ classroom }}</a>
    </li>
    <li>{{ subject }}</li>
    <li>
        <a href="{% url 'school:assignment_list' %}?classroom_id={{ classroom.id }}">{% trans 'Assignments' %}</a>
    </li>
    <li>{{ assignment.title }}</li>
    <li>{% trans 'Replies' %}</li>
{% endblock %}
{% block admin_content %}
    <div id="admin-content">
        <div class="container-fluid stage">
            <div id="admin-tools">
                <form id="admin-tools-form">
                    <div>
                        <div>
                            <i class="glyphicon glyphicon-search"></i>
                            <i class="glyphicon glyphicon-menu-left hide-search back"></i>
                            <input id="context-search" type="text" placeholder="{% trans "Search" %}" value="{% if q %}{{ q }}{% endif %}"
                                   class="input-sm tool search" data-min-search-chars="2"/>
                        </div>
                        {% if filter and filter|length > 0 %}
                            <div class="filter-trigger">
                                <i class="glyphicon glyphicon-filter"></i>
                                <i class="glyphicon glyphicon-menu-left hide-filter back"></i>
                                <div class="show-floating-filter btn btn-default btn-sm hidden-xs" style="display: none; padding-left: 30px">
                                    <div>
                                        <span class="pull-left">{% trans "Filters" %}</span>
                                        <span class="caret pull-right" style="margin: 7px 0 0 5px"></span>
                                    </div>
                                </div>
                                <div class="floating-filter subtle-shade" style="display: none">
                                    <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                </div>
                                {% for elt in filter %}
                                    <div class="tool filter{% if elt.is_date_filter %} period{% endif %}">
                                        <label for="{{ elt.parameter_name }}" class="sr-only">{% trans elt.title %}</label>
                                        <select id="{{ elt.parameter_name }}" style="float: left; width: 120px;{% if forloop.counter > 1 %} padding-left: 10px{% endif %}"
                                                class="form-control input-sm {{ elt.parameter_name }} widget" name="{{ elt.parameter_name }}">
                                            <option value="">{% trans "All" %} {% trans elt.title %}</option>
                                            {% for choice in elt.choices %}
                                                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                                            {% endfor %}
                                            {% if elt.is_date_filter %}
                                                <option value="other">{% trans "Other" %}</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                {% endfor %}
                                <div id="admin-tools-actions">
                                    {% url 'school:change_assignment' classroom_id as change_object_url %}
                                    <a href="{{ change_object_url }}" class="btn btn-sm btn-success cta add pull-right action"
                                            title="{% blocktrans %}Add new {{ verbose_name }}{% endblocktrans %}">
                                        <i class="glyphicon glyphicon-plus"></i>
                                        <span class="hidden-xs">{% trans "Add" %}</span>
                                        {% if first_setup %}<div class="pulse"></div>{% endif %}
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </form>
                <div class="clearfix"></div>
            </div>
            <div id="results" class="results-stage">
                {% include html_results_template_name %}
            </div>
        </div>
    </div>
{% endblock %}

school/templates/school/classroom/change_classroom.html
{% extends "core/change_object_base.html" %}
{% load i18n humanize static admin_list %}

{% block admin_content %}
    <div id="admin-content" class="change-form">
        <div class="container-fluid">
            {% if errors %}<p class="alert alert-danger">{{ errors }}</p>{% endif %}
            <form id="submit-classroom" class="admin-form" method="post">{% csrf_token %}
                <input type="hidden" name="object_id" value="{{ obj.id }}" />
                {% include 'core/snippets/model_admin_form.html' %}
                <formset class="subject-coefficient-list">
                    <legend>{% trans "Subjects" %}</legend>
                    <div class="row acronyms">
                        <div class="col-sm-2 col-lg-2">{% trans "Tchr" %} = {% trans "Teacher" %}</div>
                        <div class="col-sm-2 col-lg-2">{% trans "Grp" %} = {% trans "Group" %}</div>
                        <div class="col-sm-2 col-lg-2">{% trans "Coef." %} = {% trans "Coefficient" %}</div>
                        <div class="col-sm-3 col-lg-2">{% trans "LD" %} = {% trans "Lessons Due" %}</div>
                        <div class="col-sm-3 col-lg-2">{% trans "HD" %} = {% trans "Hours Due" %}</div>
                    </div>
                    <input type="hidden" id="subjects" name="subjects" />
                    {% for subject in subject_list %}
                        <div class="subject checkbox tile col-xs-6 col-sm-4 col-md-3">
                            <label for="squaredThree">
                                <input type="checkbox" value="{{ subject.id }}" {% if subject.is_active %}checked{% endif %}>
                                <strong class="hidden-xs">{{ subject.name }}</strong>
                                <strong class="visible-xs">{{ subject.name|truncatechars:"15" }}</strong>
                            </label>
                            <div>
                                <span class="sc-label">{% trans "Tchr" %}</span>
                                <select class="form-control input-sm teacher" title="{% trans "Teacher" %}">
                                    <option value="">-------</option>
                                    {% for teacher in teacher_list %}
                                        <option {% if teacher == subject.teacher %} selected{% endif %}
                                                value="{{ teacher.id }}">{{ teacher }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div>
                                <span class="sc-label">{% trans "Grp" %}</span>
                                <select class="form-control input-sm group" title="{% trans "Group" %}">
                                    {% for gp in range_1_4 %}
                                        <option{% if gp == subject.group %} selected{% endif %}>{{ gp }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div>
                                <span class="sc-label">{% trans "Coef." %}</span>
                                <input type="text" class="form-control input-sm coefficient"
                                       value="{{ subject.coefficient }}" placeholder="{% trans "Coefficient" %}"/>
                            </div>
                            <div>
                                <span class="sc-label">{% trans "LD" %}</span>
                                <input type="text" class="form-control input-sm lessons-due"
                                       value="{{ subject.lessons_due }}" placeholder="{% trans "Lessons due" %}"/>
                            </div>
                            <div>
                                <span class="sc-label">{% trans "HD" %}</span>
                                <input type="text" class="form-control input-sm hours-due"
                                       value="{{ subject.hours_due }}" placeholder="{% trans "Hours due" %}"/>
                            </div>
                        </div>
                    {% endfor %}
                </formset>
                <div class="form-group col-xs-12 col-sm-4 col-md-3" style="clear: both; padding-top: 15px">
                    <button class="btn btn-sm btn-primary btn-block">{% trans "Save" %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        (function() {
            var levelInfo = {{ level_info|safe }};
            $('#id_level').change(function() {
                var levelId = $(this).val(),
                    registrationFees = levelInfo[levelId].registration_fees,
                    firstInstalment = levelInfo[levelId].first_instalment,
                    secondInstalment = levelInfo[levelId].second_instalment,
                    thirdInstalment = levelInfo[levelId].third_instalment,
                    subjectList = levelInfo[levelId].subject_list;
                $('#id_registration_fees').val(registrationFees);
                $('#id_first_instalment').val(firstInstalment);
                $('#id_second_instalment').val(secondInstalment);
                $('#id_third_instalment').val(thirdInstalment);
                $('.subject input[type=checkbox]').prop('checked', false);
                $('.subject input[type=text]').val('');
                $('.subject').each(function() {
                    var $checkbox = $(this).find('input[type=checkbox]'),
                        $group = $(this).find('select.group'),
                        $coefficient = $(this).find('input.coefficient'),
                        $lessonsDue = $(this).find('input.lessons-due'),
                        $hoursDue = $(this).find('input.hours-due');
                    for (var i=0; i<subjectList.length; i++) {
                        if (subjectList[i].id == $checkbox.val()) {
                            $checkbox.prop('checked', true);
                            $group.val(subjectList[i].group);
                            $coefficient.val(subjectList[i].coefficient);
                            $lessonsDue.val(subjectList[i].lessons_due);
                            $hoursDue.val(subjectList[i].hours_due);
                        }
                    }
                });
            });
            $('form#submit-classroom').submit(function() {
                var doSubmit = true,
                    subjects = [];
                $('.coefficient, .lessons-due, .hours-due').removeClass('input-error');
                $('.subject').each(function() {
                    var $checkbox = $(this).find('input[type=checkbox]');
                    if ($checkbox.prop('checked')) {
                        var subjectId = $checkbox.val(),
                            teacherId = $(this).find('.teacher').val(),
                            $group = $(this).find('.group'),
                            $coefficient = $(this).find('.coefficient'),
                            $lessonsDue = $(this).find('.lessons-due'),
                            $hoursDue = $(this).find('.hours-due'),
                            group = parseInt($group.val()),
                            coefficient = parseInt($coefficient.val()),
                            lessonsDue = parseInt($lessonsDue.val()),
                            hoursDue = parseInt($hoursDue.val());
                        if (isNaN(group)) {
                            $group.addClass('input-error');
                            doSubmit = false;
                        }
                        if (isNaN(coefficient)) {
                            $coefficient.addClass('input-error');
                            doSubmit = false;
                        }
                        if (isNaN(lessonsDue)) {
                            $lessonsDue.addClass('input-error');
                            doSubmit = false;
                        }
                        if (isNaN(hoursDue)) {
                            $hoursDue.addClass('input-error');
                            doSubmit = false;
                        }
                        var item = subjectId + ':' + group + ':' + coefficient + ':' + lessonsDue + ':' + hoursDue + ':' + teacherId;
                        subjects.push(item);
                    }
                });
                $('#subjects').val(subjects.join(','));
                if (!doSubmit) {
                    var notice = "{% trans "Some fields are incorrect. Please check and fix." %}";
                    ikwen.showFloatingNotice(notice, '', 6);
                }
                return doSubmit;
            });
        })()
    </script>
{% endblock %}