conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib.auth.decorators import permission_required
from django.contrib import admin

from ikwen_webnode.webnode.views import Home, FlatPageView
from ikwen_foulassi.school.views import SchoolDetail
from ikwen_foulassi.foulassi.views import HomeSaaS as scolarfleet

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/serviceDetail/$', permission_required('accesscontrol.sudo')(SchoolDetail.as_view()),
        name='service_detail'),
    url(r'^ikwen/serviceDetail/(?P<service_id>[-\w]+)/$',
        permission_required('accesscontrol.sudo')(SchoolDetail.as_view()),  name='service_detail'),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^scolarfleet$', scolarfleet.as_view(), name='scolarfleet'),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^', include('ikwen_webnode.webnode.urls', namespace='webnode')),
)

school/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import permission_required, user_passes_test
from ikwen_foulassi.school.student.views import ChangeStudent, StudentDetail, ChangeJustificatory, ViewHomework,\
    ViewCorrection
from ikwen_foulassi.school.classroom.views import ClassroomList, ChangeClassroom, ClassroomDetail, upload_student_file, \
    AssignmentList, ChangeAssignment, ChangeAssignmentCorrection, AssignmentCorrectionList, AssignmentReplyList
from ikwen_foulassi.school.views import LevelList, ChangeLevel, SubjectList, ChangeSubject, ChangeSession, \
    SessionList, DisciplineItemList, ChangeDisciplineItem, TeacherList, TeacherDetail, SessionGroupList, \
    ChangeSessionGroup, close_session
from ikwen_foulassi.foulassi.utils import access_classroom

urlpatterns = patterns(
    '',
    url(r'^levels/$', permission_required('school.ik_manage_school')(LevelList.as_view()), name='level_list'),
    url(r'^level/$', permission_required('school.ik_manage_school')(ChangeLevel.as_view()), name='change_level'),
    url(r'^level/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeLevel.as_view()), name='change_level'),

    url(r'^subjects/$', permission_required('school.ik_manage_school')(SubjectList.as_view()), name='subject_list'),
    url(r'^subject/$', permission_required('school.ik_manage_school')(ChangeSubject.as_view()), name='change_subject'),
    url(r'^subject/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSubject.as_view()),
        name='change_subject'),

    url(r'^sessions/$', permission_required('school.ik_manage_school')(SessionList.as_view()), name='session_list'),
    url(r'^session/$', permission_required('school.ik_manage_school')(ChangeSession.as_view()), name='change_session'),
    url(r'^session/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSession.as_view()),
        name='change_session'),

    url(r'^sessionGroups/$', permission_required('school.ik_manage_school')(SessionGroupList.as_view()), name='sessiongroup_list'),
    url(r'^sessionGroup/$', permission_required('school.ik_manage_school')(ChangeSessionGroup.as_view()), name='change_sessiongroup'),
    url(r'^sessionGroup/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeSessionGroup.as_view()),
        name='change_sessiongroup'),

    url(r'^discipline/$', permission_required('school.ik_manage_school')(DisciplineItemList.as_view()), name='disciplineitem_list'),
    url(r'^disciplineItem/$', permission_required('school.ik_manage_school')(ChangeDisciplineItem.as_view()), name='change_disciplineitem'),
    url(r'^disciplineItem/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeDisciplineItem.as_view()),
        name='change_disciplineitem'),

    url(r'^classrooms/$', user_passes_test(access_classroom)(ClassroomList.as_view()), name='classroom_list'),
    url(r'^classroom/$', permission_required('school.ik_manage_school')(ChangeClassroom.as_view()), name='change_classroom'),
    url(r'^classroom/(?P<object_id>[-\w]+)/$', permission_required('school.ik_manage_school')(ChangeClassroom.as_view()),
        name='change_classroom'),
    url(r'^classroomDetail/(?P<object_id>[-\w]+)/$', user_passes_test(access_classroom)(ClassroomDetail.as_view()),
        name='classroom_detail'),

    url(r'^assignments/$', user_passes_test(access_classroom)(AssignmentList.as_view()), name='assignment_list'),
    url(r'^assignment/(?P<classroom_id>[-\w]+)/$', user_passes_test(access_classroom)(ChangeAssignment.as_view()),
        name='change_assignment'),
    url(r'^assignment/(?P<classroom_id>[-\w]+)/(?P<object_id>[-\w]+)/$',
        user_passes_test(access_classroom)(ChangeAssignment.as_view()), name='change_assignment'),
    url(r'^correction/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)/$',
        user_passes_test(access_classroom)(ChangeAssignmentCorrection.as_view()), name='change_assignment_correction'),
    url(r'^correction/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)/(?P<object_id>[-\w]+)$',
        user_passes_test(access_classroom)(ChangeAssignmentCorrection.as_view()), name='change_assignment_correction'),
    url(r'^corrections/(?P<classroom_id>[-\w]+)/(?P<subject_id>[-\w]+)$', user_passes_test(access_classroom)(AssignmentCorrectionList.as_view()),
        name='assignment_correction_list'),
    url(r'^replies/(?P<classroom_id>[-\w]+)/(?P<assignment_id>[-\w]+)$', user_passes_test(access_classroom)(AssignmentReplyList.as_view()),
        name='assignment_reply_list'),
    url(r'^homework/(?P<object_id>[-\w]+)/$', user_passes_test(access_classroom)(ViewHomework.as_view()),
        name='view_homework'),
    url(r'^homework/(?P<homework_id>[-\w]+)/correction$', user_passes_test(access_classroom)(ViewCorrection.as_view()),
        name='view_correction'),

    url(r'^upload_student_file/$', permission_required('foulassi.ik_manage_student')(upload_student_file), name='upload_student_file'),
    url(r'^newStudent/(?P<classroom_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(ChangeStudent.as_view()), name='change_student'),
    url(r'^student/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(StudentDetail.as_view()),
        name='student_detail'),
    url(r'^justificatory/$', permission_required('foulassi.ik_manage_student')(ChangeJustificatory.as_view()),
        name='change_justificatory'),
    url(r'^justificatory/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_student')(ChangeJustificatory.as_view()),
        name='change_justificatory'),

    url(r'^teachers/$', permission_required('foulassi.ik_manage_teacher')(TeacherList.as_view()), name='teacher_list'),
    url(r'^teacher/(?P<object_id>[-\w]+)/$', permission_required('foulassi.ik_manage_teacher')(TeacherDetail.as_view()), name='teacher_detail'),
    url(r'^close_session$', close_session, name='close_session'),
)

school/classroom/views.py
import csv
import json
import logging
import re
import traceback
from datetime import datetime
from copy import copy
from threading import Thread
from time import strptime

from ajaxuploader.views import AjaxFileUploader
from django.conf import settings
from django.contrib import messages
from django.contrib.humanize.templatetags.humanize import intcomma
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.core.validators import validate_email
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import slugify
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _, activate
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from ikwen.billing.models import InvoiceItem, InvoiceEntry
from ikwen.billing.utils import get_next_invoice_number
from ikwen.core.constants import MALE, FEMALE
from ikwen.core.utils import get_model_admin_instance, increment_history_field, DefaultUploadBackend, \
    get_service_instance, get_mail_content, send_push, convert_file_to_utf8
from ikwen.core.templatetags.url_utils import strip_base_alias
from ikwen.core.models import Service, Application
from ikwen.core.views import HybridListView, ChangeObjectBase
from ikwen.accesscontrol.backends import UMBRELLA

from ikwen_foulassi.foulassi.models import Student, Teacher, Invoice, get_school_year, Parent
from ikwen_foulassi.foulassi.utils import remove_student_from_parent_profile, set_student_counts, check_all_scores_set, \
    send_push_to_parents, send_billed_sms
from ikwen_foulassi.reporting.utils import set_counters, calculate_session_report, \
    calculate_session_group_report, set_stats, set_daily_counters_many
from ikwen_foulassi.foulassi.admin import StudentResource
from ikwen_foulassi.reporting.models import SessionReport, LessonReport
from ikwen_foulassi.school.admin import ClassroomAdmin, AssignmentAdmin, AssignmentCorrectionAdmin
from ikwen_foulassi.school.models import Level, Classroom, Session, get_subject_list, Subject, Score, \
    ScoreUpdateRequest, SubjectCoefficient, Lesson, Assignment, AssignmentCorrection, Homework
from ikwen_foulassi.school.student.views import set_student_invoices
from import_export.formats.base_formats import XLS

from daraja.models import DARAJA

logger = logging.getLogger('ikwen')


def import_students(filename, classroom=None, dry_run=True, set_invoices=False):
    abs_path = getattr(settings, 'MEDIA_ROOT') + filename
    try:
        convert_file_to_utf8(abs_path)
    except:
        error = "Failed to convert file to UTF-8"
        return error
    fh = open(abs_path, 'r')
    line = fh.readline()
    fh.close()
    data = line.split(',')
    delimiter = ',' if len(data) > 2 else ';'
    error = None
    row_length = 8
    row_length2 = 12  # Student info plus information of one parent. Parent info take 4 columns
    row_length3 = 16  # Student info plus information of two parent
    with open(abs_path) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=delimiter)
        i = -1
        for row in csv_reader:
            i += 1
            if i == 0:
                continue
            line = ''.join([elt.strip() for elt in row[:]])
            if not line:
                continue
            if len(row) < row_length or row_length + 1 <= len(row) < row_length2 or row_length2 + 1 <= len(row) < row_length3:
                if len(row) > row_length2:
                    expected = row_length3
                elif len(row) > row_length:
                    expected = row_length2
                else:
                    expected = row_length
                error = _("Missing information at line %(line)d. %(found)d tokens found, "
                          "but %(expected)d expected." % {'line': i + 1, 'found': len(row), 'expected': expected})
                break
            reg_num = row[0].strip()
            last_name = row[1].strip()
            if not last_name:
                error = _("Missing last name on line %d" % (i + 1))
                break
            first_name = row[2].strip()
            if not first_name:
                error = _("Missing first name on line %d" % (i + 1))
                break
            try:
                last_name.decode('utf8')
                first_name.decode('utf8')
            except:
                error = _("Unreadable student name on line %d. Please replace or remove all suspect "
                          "whitespaces and special characters in cells to avoid malicious symbols." % (i + 1))
                break

            gender = row[3].strip()
            if gender.lower().startswith("m"):
                gender = MALE
            elif gender.lower().startswith("f"):
                gender = FEMALE
            else:
                error = _("Unknown gender <strong>%(gender)s</strong> on line %(line)s. "
                          "Must be either <b>Male</b> or <b>Female</b>" % {'gender': gender, 'line': i + 1})
                break
            dob = row[4].strip()
            try:
                st = strptime(dob.replace(' ', '').replace('/', '-'), '%Y-%m-%d')
                dob = datetime(st.tm_year, st.tm_mon, st.tm_mday).date()
            except:
                try:
                    st = strptime(dob.replace(' ', '').replace('/', '-'), '%d-%m-%Y')
                    dob = datetime(st.tm_year, st.tm_mon, st.tm_mday).date()
                except:
                    error = _("Incorrect date of birth <strong>%(dob)s</strong> on line %(line)d. "
                              "Must be in the format <b>Year-Month-Day</b>" % {'dob': dob, 'line': i + 1})
                    break
            place_of_birth = row[5].strip()
            if not place_of_birth:
                error = _("Missing place of birth on line %d" % (i + 1))
                break
            try:
                place_of_birth.decode('utf8')
            except:
                error = _("Unreadable student name on line %d. Please replace or remove all suspect "
                          "whitespaces and special characters in cells to avoid malicious symbols." % (i + 1))
                break
            is_repeating = row[6].strip()
            if is_repeating.capitalize() not in ("Yes", "Y", "No", "N", "Oui", "O", "Non"):
                error = _("Incorrect Repetition <strong>%(rep)s</strong> on line %(line)d. "
                          "Must be either <b>Yes</b> or <b>No</b>" % {'rep': is_repeating, 'line': i + 1})
                break
            is_repeating = True if is_repeating in ("Yes", "Y", "Oui", "O") else False
            year_joined = row[7].strip()
            try:
                year_joined = int(year_joined)
            except ValueError:
                error = _("Year joined <strong>%(year_joined)s</strong> on line %(line)d is incorrect. "
                          "Please check." % {'year_joined': year_joined, 'line': i + 1})
                break
            year = get_school_year()
            if year_joined > year:
                error = _("Year joined <strong>%(year_joined)s</strong> on line %(line)d seems incorrect. "
                          "Please check." % {'year_joined': year_joined, 'line': i + 1})
                break

            parent1_name, parent1_relationship, parent1_email, parent1_phone = None, None, None, None
            parent2_name, parent2_relationship, parent2_email, parent2_phone = None, None, None, None

            parent1_is_set = row[8] or row[9] or row[10] or row[11]
            if parent1_is_set:  # Information for one parent were set
                parent1_name = row[8].strip()
                try:
                    parent1_name.decode('utf8')
                except:
                    error = _("Unreadable Parent 1 name on line %d. Please replace or remove all suspect "
                              "whitespaces and special characters to avoid malicious symbols." % (i + 1))
                    break
                parent1_relationship = row[9].strip()
                if not parent1_relationship:
                    error = _("Missing parent 1 relationship on line %d. Use one of "
                              "<strong>Father</strong>, <strong>Mother</strong>, <strong>Uncle</strong>, etc" % (i + 1))
                    break
                try:
                    parent1_relationship = parent1_relationship.decode('utf8')
                except:
                    error = _("Unreadable parent 1 relationship on line %d. Please replace or remove all suspect "
                              "whitespaces and special characters to avoid malicious symbols." % (i + 1))
                    break
                parent1_email = row[10].strip()
                if parent1_email:
                    try:
                        validate_email(parent1_email)
                    except ValidationError:
                        error = _("Incorrect parent 1 email <strong>%(email)s</strong> on "
                                  "line %(line)d" % {'email': parent1_email, 'line': (i + 1)})
                        break
                parent1_phone = row[11]
                if not re.match('\d{9}', slugify(parent1_phone).replace('-', '')):
                    error = _("Missing or incorrect parent 1 phone <strong>%(phone)s</strong> on line %(line)d. "
                              "Phone must be composed of 9 digits." % {'phone': parent1_phone, 'line': (i + 1)})
                    break

            parent2_is_set = row[12] or row[13] or row[14] or row[15]  # Information for second parent were set
            if parent2_is_set:
                parent2_name = row[12].strip()
                try:
                    parent2_name.decode('utf8')
                except:

school/templates/school/snippets/classroom/assignment_correction_list_results.html
{% load i18n static humanize %}
{% include 'core/snippets/spinner.html' %}
<style>
    @media (min-width: 990px) {
        .actions i {top: 12px}
    }

</style>
<ul class="object-list list-group">
    {% for obj in objects_page.object_list %}
        {% url 'school:change_assignment_correction' classroom.id obj.assignment.id obj.id as obj_url %}
        <li class="ik-li list-group-item {{ obj.status }}" id="{{ obj.id }}" data-id="{{ obj.id }}">
            <a class="hidden-xs" href="{{ obj_url }}">{{ obj }}</a>
            <a class="visible-xs" href="{{ obj_url }}">{{ obj|truncatechars:30 }}</a>
            <date class="date text-muted">{{ obj.created_on }}</date>
            {% with obj_details=obj.get_obj_details %}
                {% if obj_details %}
                    <div class="text-muted">{{ obj_details|safe }}</div>
                {% endif %}
            {% endwith %}
            <div class="actions">
                {% if has_is_active_field %}
                    {% if obj.is_active %}
                        <i class="action glyphicon glyphicon-ok toggle active off" title="{% trans "Deactivate" %}"></i>
                    {% else %}
                        <i class="action glyphicon glyphicon-ok toggle active on" title="{% trans "Activate" %}"></i>
                    {% endif %}
                {% endif %}
                <i class="glyphicon glyphicon-trash trash" title="{% trans "Delete item" %}"></i>
            </div>
        </li>
    {% endfor %}
</ul>
{% if objects_page.paginator.num_pages > 1 %}
<ul class="pagination">
    {% if objects_page.paginator.num_pages > max_visible_page_count and page_range.0 >= max_visible_page_count  %}
        <li class="page" data-val="first"><a href="javascript:;" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
    {% endif %}
    {% for page in page_range %}
        <li class="page{% if page == objects_page.number %} active{% endif %}" data-val="{{ page }}">
            <a href="javascript:;">
                {{ page }} {% if page == objects_page.number %}<span class="sr-only">(current)</span>{% endif %}
            </a>
        </li>
    {% endfor %}
    {% if objects_page.paginator.num_pages > max_visible_page_count and max_page < objects_page.paginator.num_pages %}
        <li class="page{% if max_page == objects_page.paginator.num_pages %} disabled{% endif %}" data-val="-1"><a href="javascript:;" aria-label="Next"><span aria-hidden="true">»</span></a></li>
    {% endif %}
</ul>
{% endif %}
<div id="page-navigation" class="text-muted">
    {% if objects_page.paginator.num_pages > 1 %}
        <p>{% blocktrans with count=objects_page.paginator.count start=objects_page.start_index end=objects_page.end_index %}
            {{ start }} – {{ end }} of {{ count }} results{% endblocktrans %}</p>
    {% else %}
        <p>{% blocktrans with count=objects_page.paginator.count %}{{ count }} results{% endblocktrans %}</p>
    {% endif %}
</div>

school/templates/school/snippets/classroom/assignment_list_results.html
{% load i18n static humanize %}
{% include 'core/snippets/spinner.html' %}
<ul class="object-list list-group">
    {% for obj in objects_page.object_list %}
    {% url 'school:change_assignment' classroom_id obj.id as obj_url %}
    <li class="ik-li list-group-item {{ obj.status }}" id="{{ obj.id }}" data-id="{{ obj.id }}">
        <a class="hidden-xs" href="{{ obj_url }}">{{ obj }}</a>
        <a class="visible-xs" href="{{ obj_url }}">{{ obj|truncatechars:30 }}</a>
        <date class="date text-muted">{{ obj.created_on }}</date>
        {% with obj_details=obj.get_obj_details %}
            {% if obj_details %}
                <div class="text-muted">{{ obj_details }}</div>
            {% endif %}
        {% endwith %}
        <div class="actions">
            {% if has_is_active_field %}
                {% if obj.is_active %}
                    <i class="action glyphicon glyphicon-ok toggle active off" title="{% trans "Deactivate" %}"></i>
                {% else %}
                    <i class="action glyphicon glyphicon-ok toggle active on" title="{% trans "Activate" %}"></i>
                {% endif %}
            {% endif %}
            <i class="glyphicon glyphicon-trash trash" title="{% trans "Delete item" %}"></i>
        </div>
    </li>
    {% endfor %}
</ul>
{% if objects_page.paginator.num_pages > 1 %}
<ul class="pagination">
    {% if objects_page.paginator.num_pages > max_visible_page_count and page_range.0 >= max_visible_page_count  %}
        <li class="page" data-val="first"><a href="javascript:;" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
    {% endif %}
    {% for page in page_range %}
        <li class="page{% if page == objects_page.number %} active{% endif %}" data-val="{{ page }}">
            <a href="javascript:;">
                {{ page }} {% if page == objects_page.number %}<span class="sr-only">(current)</span>{% endif %}
            </a>
        </li>
    {% endfor %}
    {% if objects_page.paginator.num_pages > max_visible_page_count and max_page < objects_page.paginator.num_pages %}
        <li class="page{% if max_page == objects_page.paginator.num_pages %} disabled{% endif %}" data-val="-1"><a href="javascript:;" aria-label="Next"><span aria-hidden="true">»</span></a></li>
    {% endif %}
</ul>
{% endif %}
<div id="page-navigation" class="text-muted">
    {% if objects_page.paginator.num_pages > 1 %}
        <p>{% blocktrans with count=objects_page.paginator.count start=objects_page.start_index end=objects_page.end_index %}
            {{ start }} – {{ end }} of {{ count }} results{% endblocktrans %}</p>
    {% else %}
        <p>{% blocktrans with count=objects_page.paginator.count %}{{ count }} results{% endblocktrans %}</p>
    {% endif %}
</div>

school/templates/school/snippets/classroom/assignment_reply_list_results.html
{% load i18n static humanize %}
{% include 'core/snippets/spinner.html' %}
<style>
    @media (min-width: 990px) {
        .actions i {top: 12px}
    }

</style>
<ul class="object-list list-group">
    {% for obj in objects_page.object_list %}
        <li class="ik-li list-group-item {{ obj.status }}" id="{{ obj.id }}" data-id="{{ obj.id }}">
            <h4 class="hidden-xs pull-left">{{ obj.student }}</h4>
            <h4 class="visible-xs pull-left">{{ obj.student|truncatechars:30 }}</h4>
            <date class="date text-muted">{{ obj.created_on|date:"Y/m/d" }}</date>
            {% with obj_details=obj.get_obj_details %}
                {% if obj_details %}
                    <div class="text-muted">{{ obj_details }}</div>
                {% endif %}
            {% endwith %}
            <div class="actions">
                {% if has_is_active_field %}
                    {% if obj.is_active %}
                        <i class="action glyphicon glyphicon-ok toggle active off" title="{% trans "Deactivate" %}"></i>
                    {% else %}
                        <i class="action glyphicon glyphicon-ok toggle active on" title="{% trans "Activate" %}"></i>
                    {% endif %}
                {% endif %}
                <a href="{{ settings.IKWEN_MEDIA_URL }}{{ obj.attachment.name }}" target="_blank" download="{{ obj.attachment.name }}">
                    <i class="fas fa-file-download" title="{% trans "Download" %}"></i>
                </a>
            </div>
        </li>
    {% endfor %}
</ul>
{% if objects_page.paginator.num_pages > 1 %}
<ul class="pagination">
    {% if objects_page.paginator.num_pages > max_visible_page_count and page_range.0 >= max_visible_page_count  %}
        <li class="page" data-val="first"><a href="javascript:;" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
    {% endif %}
    {% for page in page_range %}
        <li class="page{% if page == objects_page.number %} active{% endif %}" data-val="{{ page }}">
            <a href="javascript:;">
                {{ page }} {% if page == objects_page.number %}<span class="sr-only">(current)</span>{% endif %}
            </a>
        </li>
    {% endfor %}
    {% if objects_page.paginator.num_pages > max_visible_page_count and max_page < objects_page.paginator.num_pages %}
        <li class="page{% if max_page == objects_page.paginator.num_pages %} disabled{% endif %}" data-val="-1"><a href="javascript:;" aria-label="Next"><span aria-hidden="true">»</span></a></li>
    {% endif %}
</ul>
{% endif %}
<div id="page-navigation" class="text-muted">
    {% if objects_page.paginator.num_pages > 1 %}
        <p>{% blocktrans with count=objects_page.paginator.count start=objects_page.start_index end=objects_page.end_index %}
            {{ start }} – {{ end }} of {{ count }} results{% endblocktrans %}</p>
    {% else %}
        <p>{% blocktrans with count=objects_page.paginator.count %}{{ count }} results{% endblocktrans %}</p>
    {% endif %}
</div>

school/templates/school/snippets/classroom/student_list.html
{% load i18n static index %}
{% for student in student_list %}
    <li id="{{ student.id }}" class="ik-li member{% if student.is_excluded %} excluded{% endif %}" data-id="{{ student.id }}">
        {% if perms.school.ik_manage_student and not student.is_excluded %}
            {% url 'school:student_detail' student.id as student_url %}
        {% endif %}
        {% if student.photo.name %}
            <a href="{{ student_url|default_if_none:"javascript:;" }}" class="photo" style="background-image: url({{ settings.IKWEN_MEDIA_URL }}{{ student.photo.small_name }})"></a>
        {% else %}
            <a href="{{ student_url|default_if_none:"javascript:;" }}" class="photo" style="background-image: url({% static 'ikwen/img/login-avatar.jpg' %})"></a>
        {% endif %}
        <span class="hidden tags">{{ student.tags }}</span>
        <div class="info">
            <a href="{{ student_url|default_if_none:"javascript:;" }}" class="full_name">{{ student }}</a>
            {% if perms.school.ik_access_scores %}
                <div class="scores">
                    {% for score in student.scores|index:i %}
                        <span class="score score-{{ score.value|floatformat:"0" }}">{{ score.value }}</span>
                    {% endfor %}
                </div>
                {% if not student.is_excluded %}
                <div class="form-group input-score tpl">
                    <input type="number" class="form-control input-sm" placeholder="10.0" step="0.25" max="20" tabindex="{{ forloop.counter }}" />
                </div>
                {% endif %}
            {% else %}
                <p class="about">{{ student.dob }}</p>
            {% endif %}
        </div>
        {% if perms.school.ik_manage_student and not student.is_confirmed %}
            <div class="actions">
                <i class="glyphicon glyphicon-trash trash" title="{% trans "Delete student" %}"></i>
            </div>
        {% endif %}
    </li>
{% endfor %}