conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib.auth.decorators import permission_required
from django.contrib import admin

from ikwen_webnode.webnode.views import Home, FlatPageView
from ikwen_foulassi.school.views import SchoolDetail
from ikwen_foulassi.foulassi.views import HomeSaaS as scolarfleet

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/serviceDetail/$', permission_required('accesscontrol.sudo')(SchoolDetail.as_view()),
        name='service_detail'),
    url(r'^ikwen/serviceDetail/(?P<service_id>[-\w]+)/$',
        permission_required('accesscontrol.sudo')(SchoolDetail.as_view()),  name='service_detail'),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),

    url(r'^scolarfleet$', scolarfleet.as_view(), name='scolarfleet'),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),

    url(r'^', include('ikwen_webnode.webnode.urls', namespace='webnode')),
)

foulassi/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from ikwen_foulassi.foulassi.views import KidList, KidDetail, ShowJustificatory, AccessDenied, \
    Home, HomeSaaS, SearchSchool, EventList, DeployCloud, SuccessfulDeployment, AdminHome, ChangeHomework, \
    DownloadApp, TermsAndConditions, DownloadCorrection, BuyWebsite
from ikwen_foulassi.foulassi.cash_in import confirm_invoice_payment, confirm_my_kids_payment,\
    confirm_correction_payment

urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^for-schools$', HomeSaaS.as_view(), name='home_saas'),
    url(r'^events/$', permission_required('foulassi.ik_view_event')(EventList.as_view()), name='event_list'),
    url(r'^scolarfleet/deploy$', login_required(DeployCloud.as_view()), name='deploy_cloud'),
    url(r'^terms-and-conditions/$', login_required(TermsAndConditions.as_view()), name='terms_and_conditions'),
    url(r'^successfulDeployment/(?P<ikwen_name>[-\w]+)$', login_required(SuccessfulDeployment.as_view()), name='successful_deployment'),
    url(r'^home/$', AdminHome.as_view(), name='admin_home'),
    url(r'^buyWebsite/(?P<school_name>[-\w]+)$', login_required(BuyWebsite.as_view()), name='buy_website'),

    url(r'^search/$', login_required(SearchSchool.as_view()), name='search_school'),
    url(r'^downloadApp/$', DownloadApp.as_view(), name='download_app'),
    url(r'^kids/$', login_required(KidList.as_view()), name='kid_list'),
    url(r'^accessDenied/$', AccessDenied.as_view(), name='access_denied'),
    url(r'^confirm_invoice_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_invoice_payment, name='confirm_invoice_payment'),
    url(r'^confirm_my_kids_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_my_kids_payment, name='confirm_my_kids_payment'),
    url(r'^confirm_correction_payment/(?P<tx_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_correction_payment, name='confirm_correction_payment'),

    url(r'^(?P<ikwen_name>[-\w]+)/kid/(?P<student_id>[-\w]+)/(?P<assignment_id>[-\w]+)/download-correction$',
        login_required(DownloadCorrection.as_view()), name='download_correction'),
    url(r'^(?P<ikwen_name>[-\w]+)/kid/(?P<student_id>[-\w]+)$', login_required(KidDetail.as_view()), name='kid_detail'),
    url(r'^(?P<ikwen_name>[-\w]+)/kid/(?P<student_id>[-\w]+)/(?P<assignment_id>[-\w]+)$', login_required(ChangeHomework.as_view()), name='change_homework'),
    url(r'^(?P<ikwen_name>[-\w]+)/kid/(?P<student_id>[-\w]+)/(?P<assignment_id>[-\w]+)/(?P<homework_id>[-\w]+)$', login_required(ChangeHomework.as_view()), name='change_homework'),
    url(r'^(?P<ikwen_name>[-\w]+)/justificatory/(?P<object_id>[-\w]+)$', login_required(ShowJustificatory.as_view()),
        name='show_justificatory'),
)

foulassi/models.py
from datetime import datetime
from threading import Thread

from django.conf import settings
from django.contrib.auth.models import Group
from django.db import models
from django.db.models.signals import post_save
from django.template import Context
from django.template.loader import get_template
from django.utils.module_loading import import_by_path
from django.utils.translation import gettext_lazy as _
from django_mongodb_engine.contrib import MongoDBManager
from djangotoolbox.fields import ListField, EmbeddedModelField

from ikwen.accesscontrol.models import Member
from ikwen.core.constants import GENDER_CHOICES
from ikwen.core.utils import get_service_instance, add_database
from ikwen.core.models import Model, AbstractConfig, Service
from ikwen.core.fields import MultiImageField, FileField
from ikwen.theming.models import Theme
from ikwen.billing.models import AbstractInvoice, AbstractPayment
from permission_backend_nonrel.models import UserPermissionList

TEACHERS = "Teachers"
BEST_OF_ALL = "BestOfAll"
AVERAGE_OF_ALL = "AverageOfAll"

# Event types
ALL_SCORES_SET = "AllScoresSet"
LOW_EMAIL_CREDIT = "LowEmailCredit"
LOW_SMS_CREDIT = "LowSMSCredit"
REPORT_CARDS_GENERATED = "ReportCardsGenerated"
REPORT_CARDS_FAILED_TO_GENERATE = "ReportCardsFailedToGenerate"
PARENT_REQUEST_KID = "ParentRequestKid"


def get_school_year(request=None):
    if request:
        return request.session.get('school_year', get_school_year())
    now = datetime.now()
    month = now.month
    if 8 <= month <= 12:
        return now.year
    return now.year - 1


class Teacher(Model):
    member = models.ForeignKey(Member)
    school_year = models.IntegerField(default=get_school_year, db_index=True)

    class Meta:
        unique_together = ('member', 'school_year')

    def __unicode__(self):
        return self.member.full_name

    def get_classroom_list(self):
        from ikwen_foulassi.school.models import Classroom
        classroom_fk_list = set([])
        for obj in self.teacherresponsibility_set.all():
            classroom_fk_list = classroom_fk_list | set(obj.classroom_fk_list)
        for fk in classroom_fk_list:
            try:
                yield Classroom.objects.get(pk=fk)
            except:
                pass

    def get_subject_list(self, classroom):
        for obj in self.teacherresponsibility_set.all():
            if classroom.id in obj.classroom_fk_list:
                yield obj.subject


class Student(Model):
    UPLOAD_TO = 'foulassi/students'
    school = models.ForeignKey(Service, blank=True, null=True,
                               related_name='+', default=get_service_instance)
    registration_number = models.CharField(_("Registration number"), blank=True, max_length=30, unique=True)
    first_name = models.CharField(_("First name"), max_length=100, db_index=True)
    last_name = models.CharField(_("Last name"), max_length=100, db_index=True)
    gender = models.CharField(_("Gender"), max_length=15, choices=GENDER_CHOICES, db_index=True)
    dob = models.DateField(_("Date of birth"), db_index=True)
    pob = models.CharField(_("Place of birth"), max_length=150, blank=True, null=True, db_index=True)
    birthday = models.IntegerField(blank=True, null=True, db_index=True)
    photo = MultiImageField(upload_to=UPLOAD_TO, blank=True, null=True,
                            max_size=600, small_size=200, thumb_size=100, editable=False)
    classroom = models.ForeignKey('school.Classroom', verbose_name=_("Classroom"))
    is_repeating = models.BooleanField(_("Repeats the class ?"), default=False)
    year_joined = models.IntegerField(_("Year joined"), default=get_school_year, db_index=True,
                                      help_text=_("Year when student joined this school"))
    score_history = ListField()
    school_year = models.IntegerField(default=get_school_year, db_index=True)
    is_confirmed = models.BooleanField(default=False)  # Confirmed student cannot be deleted again
    is_excluded = models.BooleanField(default=False)  # Excluded student does not appear in classroom student list
    tags = models.TextField(blank=True, null=True, db_index=True)
    my_kids_expiry = models.DateTimeField(blank=True, null=True)
    my_kids_expired = models.BooleanField(default=True)
    has_new = models.BooleanField(default=False,
                                  help_text="Whether there's a new information published on this student: "
                                            "score, discipline information or invoice.")

    def __unicode__(self):
        return self.last_name + ' ' + self.first_name

    def save(self, **kwargs):
        if not self.id:  # Generate registration number for newly created students
            self.generate_registration_number()
        if not self.birthday and self.dob:
            self.birthday = int(self.dob.strftime('%m%d'))
        super(Student, self).save(**kwargs)

    def get_score_list(self, subject, using='default'):
        from ikwen_foulassi.school.models import Score
        return Score.objects.using(using).filter(student=self, subject=subject).order_by('session')

    def set_has_new(self, using='default'):
        """
        Checks whether there's anything new about the Student and sets
        Student.has_new to True, else sets it to False.
        """
        from ikwen_foulassi.foulassi.models import Invoice
        from ikwen_foulassi.school.models import Score, DisciplineLogEntry, Assignment
        now = datetime.now()
        has_pending_assignment = Assignment.objects.using(using).filter(classroom=self.classroom, deadline__lt=now)
        has_pending_invoice = Invoice.objects.using(using).filter(student=self, status=Invoice.PENDING).count() > 0
        has_new_discipline_info = DisciplineLogEntry.objects.using(using).filter(student=self, was_viewed=False).count() > 0
        has_new_score = Score.objects.using(using).filter(student=self, was_viewed=False).count() > 0
        self.has_new = has_pending_assignment or has_pending_invoice or has_new_discipline_info or has_new_score

    def generate_registration_number(self):
        if self.registration_number:
            return
        school_year = str(get_school_year())[-2:]
        classroom = self.classroom
        level = classroom.level
        classroom_info = level.name[0] + level.name[-1] + classroom.name[0]
        inc = Student.objects.filter(classroom=self).count() + 1
        registration_number = ''
        while True:
            try:
                registration_number = "%s%s%s" % (school_year, classroom_info, str(inc).zfill(3))
                Student.objects.get(registration_number=registration_number.upper())
                inc += 1
            except:
                break
        self.registration_number = registration_number.upper()


class Parent(Model):
    """
    Parent of a Student. Can either be a newly created object
    or can point to an ikwen.Member
    """
    student = models.ForeignKey(Student)
    member = models.ForeignKey(Member, blank=True, null=True,
                               db_index=False)  # Create index manually in production, setting it to False make unit tests work
    name = models.CharField(max_length=100, blank=True, null=True, db_index=True,
                            help_text=_("Full name of the person"))
    phone = models.CharField(max_length=30, blank=True, null=True, db_index=True)
    email = models.CharField(max_length=100, blank=True, null=True, db_index=True)
    relation = models.CharField(max_length=30, db_index=True,
                                help_text=_("Relationship that links the person to the student"))

    def get_name(self):
        if self.member:
            return self.member.full_name
        return self.name

    def get_phone(self):
        if self.member:
            return self.member.phone
        return self.phone

    def get_email(self):
        if self.member:
            return self.member.email
        return self.email

    def __unicode__(self):
        return self.name


class ParentProfile(Model):
    member = models.ForeignKey(Member)
    student_fk_list = ListField()

    def _get_student_list(self):
        student_fk_list = list(self.student_fk_list)
        student_list = []
        for student_id in student_fk_list:
            try:
                student_list.append(Student.objects.get(pk=student_id, school_year=get_school_year()))
            except Student.DoesNotExist:
                self.student_fk_list.remove(student_id)
                self.save()
        return student_list
    student_list = property(_get_student_list)


class StudentsPopulation(models.Model):
    girls_count = models.IntegerField(default=0)
    boys_count = models.IntegerField(default=0)
    school_year = models.IntegerField(default=get_school_year, db_index=True)

    def _get_student_count(self):
        return self.girls_count + self.boys_count
    student_count = property(_get_student_count)

    class Meta:
        abstract = True


class ResultsTracker(StudentsPopulation):
    girls_participation_history = ListField()
    girls_highest_score_history = ListField(EmbeddedModelField('school.Score'))
    girls_lowest_score_history = ListField(EmbeddedModelField('school.Score'))
    girls_avg_score_history = ListField()
    girls_success_history = ListField()

    boys_participation_history = ListField()
    boys_highest_score_history = ListField(EmbeddedModelField('school.Score'))
    boys_lowest_score_history = ListField(EmbeddedModelField('school.Score'))
    boys_avg_score_history = ListField()
    boys_success_history = ListField()

    class Meta:
        abstract = True

    def _get_participation_history(self):
        return [sum(x) for x in zip(self.girls_participation_history, self.boys_participation_history)]
    participation_history = property(_get_participation_history)

    def _get_highest_score_history(self):

foulassi/templates/foulassi/snippets/change_homework.html
{% load i18n static %}

<link rel='stylesheet' href="{% static 'foulassi/css/homework.css' %}?v=20.10.16" />

<div class="col-sm-8">
    {% if errors %}<p class="alert alert-danger">{{ errors }}</p>{% endif %}
    <form class="admin-form" action="{% url 'foulassi:change_homework' ikwen_name student.id assignment.id %}" method="post">{% csrf_token %}
        <h3>{{ assignment.subject }}:</h3><h4 style="line-height: 30px"> {{ assignment.title }}</h4>
        <div style="margin-top: 60px">
            <h4>{% trans "Instructions" %}:</h4>
            <p style="font-size: 20px">
                {{ assignment.detail|safe }}
            </p>
        </div>
        <div class="hidden field-box field-assignment form-group{% if not field.is_readonly and field.errors %} errors{% endif %}">
            {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
            <label class="required" for="id_assignment">{% trans 'Assignment' %}:</label>
            <input type="hidden" name="assignment" value="{{ assignment.id }}">
            <input type="text" id="id_assignment" value="{{ assignment }}" class="form-control input-sm" disabled>
        </div>
        <div class="hidden field-box field-student form-group{% if not field.is_readonly and field.errors %} errors{% endif %}">
            {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
            <label class="required" for="id_student">{% trans 'Student' %}:</label>
            <input type="hidden" name="student" value="{{ student.id }}">
            <input type="text" id="id_student" value="{{ student }}" class="form-control input-sm" disabled>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>

        {% if not deadline_reached %}
            <div style="margin-top: 80px;">
                <h3>{% trans 'Answer to assignment by uploading a file' %}</h3>
                <div>
                    {% for media_obj in media_field_list %}
                        <div class="col-sm-4 col-lg-3" style="padding-left: 0; margin-right: 15px">
                            <div>
                                {% with media=media_obj %}
                                    {% include 'core/snippets/media_uploader_single.html' %}
                                {% endwith %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form-group col-xs-12 col-sm-4 col-md-3" style="clear: both; padding-top: 15px">
                        <button class="btn btn-sm btn-primary btn-block save-homework">{% trans "Save" %}</button>
                        {% include 'core/snippets/spinner.html' %}
                    </div>
                </div>
            </div>
        {% endif %}

    </form>
</div>
<script>
    (() => {
       $('body').on('click', '.save-homework', (e) => {
          $('#student-assignments .spinner').fadeIn();
           {#let href = $(e.target).prop('href');#}
           {#$(this).load(href);#}
           {#return false;#}
       });
       $('#selection-control').addClass('back');
       $('#selection-control .clear-selection').attr('title', "{% trans 'Back' %}");
       $('#selection-control .select-count').html("{% trans 'Back' %}");
    })()
</script>

foulassi/templates/foulassi/snippets/download_correction.html
{% load i18n static humanize %}
<link rel='stylesheet' href="{% static 'foulassi/css/homework.css' %}?v=20.10.02" />

<div class="container download-correction">
    <div class="col-sm-offset-1 col-sm-9">
        {% if correction %}
            <h3 class="title">{{ assignment.title }}</h3>
            <h5 class="text-muted">{{ assignment.subject }}&nbsp;&nbsp;&compfn;&nbsp;&nbsp;
                <time class="date" style="float: none">{{ correction.created_on }}</time>
            </h5>
            <span class="badge badge-info" style="margin-bottom: 50px; padding: 7px">{% trans 'Correction' %}</span>
            {% if correction.cost > 0 and not invoice %}
                <div class="cost">
                    <span class="h4 header">{% trans 'Cost:' %}</span>
                    <sup class="crncy">XAF</sup>
                    <span class="header h1">&nbsp;&nbsp;{{ correction.cost|intcomma }}</span>
                </div>
                <button type="button" class="btn btn-md btn-deep-blue col-sm-3 col-xs-12 payment-start purchase-correction"
                        data-product-id="{{ correction.id }}">
                    <i class="fas fa-money" aria-hidden="true"></i>
                    {% trans 'Purchase' %}
                </button>
            {% else %}
                <a href="{% get_media_prefix %}{{ correction.attachment }}"
                   class="btn  btn-deep-blue btn-md col-sm-3 col-xs-12"
                   download="{{ correction }}{{ extension }}" target="_blank">
                    <i class="fas fa-download" style="margin-right: 12px"></i>
                    {% trans "Download" %}
                </a>
            {% endif %}
        {% else %}
            <div class="text-center text-muted no-correction">
                <em>{% blocktrans %}Correction of {{ assignment }} is not yet available{% endblocktrans %}</em>
            </div>
        {% endif %}
    </div>
</div>
<script>
    (() => {
        $('#selection-control').addClass('back');
        $('#selection-control .clear-selection').attr('title', "{% trans 'Back' %}");
        $('#selection-control .select-count').html("{% trans 'Back' %}");

        $('#amount').val('{{ correction.cost }}');

    })()
</script>

foulassi/templates/foulassi/snippets/kid_list_nav.html
{% load i18n humanize static %}

{% block admin_nav %}
    <div id="admin-nav" class="edge-panel-left">
        <a href="{% url 'foulassi:kid_list' %}" class="title-brand">Foulassi</a>
        <div class="wrapper">
            <div class="stage">
                <div class="menu">
                    <ul class="object-list people">
                        {% for kid in kid_list %}
                        {% url 'foulassi:kid_detail' kid.school.ikwen_name kid.id as kid_url %}
                        <li class="ik-li member">
                            <a href="{{ kid_url }}" style="display: block; margin: 0 -15px 0 -10px">
                                {% if kid.photo.name %}
                                    <div class="photo bg-img" style="background-image: url({% get_media_prefix %}{{ kid.photo.name }})"></div>
                                {% else %}
                                    <div class="photo bg-img" style="background-image: url({% get_static_prefix %}ikwen/img/member-avatar.jpg)"></div>
                                {% endif %}
                                <div class="info">
                                    <span class="full_name">{{ kid }}</span>
                                    <p class="about">
                                        <span class="phone">{{ kid.school.project_name }}</span>
                                    </p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
{% endblock %}

foulassi/templates/foulassi/snippets/mykids_color_and_icons.html
{% load i18n static cache %}

<meta name="theme-color" content="#fff">

<meta name="msapplication-TileColor" content="#fff">
<meta name="msapplication-navbutton-color" content="#fff">
<meta name="msapplication-TileImage" content="{% static 'foulassi/mykids/icons/icon-144x144.png' %}">

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#fff">

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'foulassi/mykids/icons/icon-180x180.png' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'foulassi/mykids/icons/icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'foulassi/mykids/icons/icon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'foulassi/mykids/icons/icon-32x32.png' %}">

foulassi/templates/foulassi/snippets/scolarfleet_color_and_icons.html
{% load i18n static cache %}

<meta name="theme-color" content="#fff">

<meta name="msapplication-TileColor" content="#fff">
<meta name="msapplication-navbutton-color" content="#fff">
<meta name="msapplication-TileImage" content="{% static 'foulassi/scolarfleet/icons/icon-144x144.png' %}">

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#fff">

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'foulassi/scolarfleet/icons/icon-180x180.png' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'foulassi/scolarfleet/icons/icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'foulassi/scolarfleet/icons/icon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'foulassi/scolarfleet/icons/icon-32x32.png' %}">

foulassi/templates/foulassi/snippets/send_message_modals.html
{% load i18n humanize static auth_tokens %}
<div class="modal fade" id="send-sms-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-info">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div>
                    <div class="text-right">
                        <strong class="sms-balance" data-sms-balance="{{ sms_balance }}">2580</strong>
                        <em class="text-muted">Credits remaining</em>
                    </div>
                    <div class="form-group" style="margin-bottom: 5px">
                        <label for="sms-text">{% trans 'Text' %}</label>
                        <textarea id="sms-text" class="sms-text form-control"
                                  style="height: 120px"></textarea>
                    </div>
                    <div>
                        <span class="pull-left sms-char-count text-muted">151</span>
                        <span class="text-center pull-left" style="width: 30px">-</span>
                        <span class="pull-left sms-page-count">1/3</span>
                        <span class="pull-right">
                            <strong class="sms-credits-needed">15</strong>
                            <em class="text-muted">{% trans "Credits" %}</em>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                    <div class="insufficient-credit text-danger text-right">{% blocktrans %}
                        Insufficient SMS Credit - <a href="#">Refill</a>
                    {% endblocktrans %}</div>
                    <div class="clearfix"></div>
                </div>
                <div class="actions row">
                    <div class="col-xs-12 col-sm-4 col-md-3 pull-right">
                        <button class="btn btn-sm btn-success btn-block do-send-sms"
                                data-dismiss="modal" aria-label="Close">{% trans "OK" %}</button>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-3 pull-right">
                        <button class="btn btn-sm btn-default btn-block"
                                data-dismiss="modal" aria-label="Close">{% trans "Cancel" %}</button>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="send-mail-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-info">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div>
                    <div class="text-right">
                        <strong class="mail-balance" data-mail-balance="{{ mail_balance }}">8250</strong>
                        <em class="text-muted">Credits remaining</em>
                    </div>
                    <div class="form-group" style="margin-bottom: 5px">
                        <label for="mail-text">{% trans 'Text' %}</label>
                        <textarea id="mail-text" class="mail-text form-control"
                                  style="height: 120px"></textarea>
                    </div>
                    <div>
                        <span class="pull-right">
                            <strong class="mail-credits-needed">{{ classroom.size }}</strong>
                            <em class="text-muted">{% trans "Credits" %}</em>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                    <div class="insufficient-credit text-danger text-right">{% blocktrans %}
                        Insufficient Mail Credit - <a href="#">Refill</a>
                    {% endblocktrans %}</div>
                    <div class="clearfix"></div>
                </div>
                <div class="actions row">
                    <div class="col-xs-12 col-sm-4 col-md-3 pull-right">
                        <button class="btn btn-sm btn-success btn-block do-send-sms"
                                data-dismiss="modal" aria-label="Close">{% trans "OK" %}</button>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-3 pull-right">
                        <button class="btn btn-sm btn-default btn-block"
                                data-dismiss="modal" aria-label="Close">{% trans "Cancel" %}</button>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

foulassi/templates/foulassi/snippets/splash_screen.html
{% load i18n static %}
<div class="splash-screen">
    <div class="logo">
        <img />
    </div>
    <div class="widgets">
        <div class="gauge">
            <div class="fill"></div>
        </div>
        <p class="catchy">{% trans "Connected School Management Platform !" %}</p>
    </div>
</div>
<script>
    (function() {
        var imageUrl = "{% static 'foulassi/img/foulassi_splash.png' %}",
            img = new Image();
        img.onload = function() {
            $('.splash-screen img').attr('src', imageUrl);
        };
        img.src = imageUrl;
        $('.splash-screen img').animate({height: '100%'}, 'slow');
        $('.splash-screen .fill').animate({width: '100%'}, 2000, 'linear', function() {
            $('.splash-screen').delay(1500).fadeOut('slow');
        });
    })()
</script>